### ISSUE TITLE
Milestone 2 

### ISSUE THREAD

**Issue by jasmineortega** [UBC-MDS/imghelp#10]
Individual function work:
- [x] Write unit test function (3-5 edge cases) 
- [x] Write internal code for function
- [x] Ensure code passes unit test (via pytest)

Gropl:
- [x] Package able to be installed from GitHub

R to-dos ~ (R Repo Checkpoints: https://github.com/UBC-MDS/ImgHelpR/issues/4)
- [x] Create project structure
- [x] MIT license
- [x] Code of Conduct
- [x] DESCRIPTION file
- [x] CONTRIBUTING.md
- [x] README.Rmd
- [x] R package function specifications

**Comment by jasmineortega** [comment]
We should also go over our Milestone 1 feedback in lab!

**Comment by MaeveShi** [comment]
`This group was pushing their changes into the main branch, meaning that this group has not set up protection for the main branch`

We deleted all the branches so it looks like we are working directly in the main branch...

**Comment by Kendy-Tan** [comment]
I thought we need to delete all other branches after merging to the main branch? So I did that.

`Github workflow ok, but you guys did not use milestones.`

We did create a milestones1 checklist and it's closed after all is done. I'm not sure if that's the milestones he was looking for
