### ISSUE TITLE
Milestone 1 Checklist

### ISSUE THREAD

**Issue by jasmineortega** [UBC-MDS/imghelp#4]
Set-up:
-  [x] Team work contract
-  [x] Pick topic/name

Project Structure:
- [x] Project Structure  (cookiecutter)
- [x] License
- [x] CONDUCT.md
- [x] CONTRIBUTING.md
- [x] README.md: CONTRIBUTORS 
- [x] README.md: outline 

Function Specifications:
- [x] Crop
- [x] Rotate
- [x] ColorConversion
- [x] Compression

- [x] Delete excess branches
